### ISSUE TITLE
Question about addon

### ISSUE THREAD

**Issue by obeyler** [vmware/harbor-boshrelease#13]
Why do you add your own bosh-dns or syslog instead of official release from bosh.io ?
On our CF plateform we already have them and they conflict with yours. 
I can't remove your add-on present into the harbor manifest as the name used is not the same and you have dependency into your monit :-(

**Comment by jessehu** [comment]
Sorry for the late response.

https://github.com/vmware/harbor-boshrelease/blob/master/manifests/runtime-config-bosh-dns.yml is the standard bosh-dns addon. You do not need to upload it if already have it on your CF.

https://github.com/vmware/harbor-boshrelease/blob/master/manifests/runtime-config-harbor.yml is required by Harbor to resolve user specified Harbor hostname.

**Comment by jessehu** [comment]
does the file 'wait' has +x permission ? What's the result of executing "/var/vcap/jobs/bosh-dns/bin/wait" on the harbor VM as root user? What's your bosh-dns release version?

**Comment by obeyler** [comment]
yes is has  +x permission
4 -rwxr-xr-x 1 root root 109 May 25 16:16 /var/vcap/jobs/bosh-dns/bin/wait

the result of wait is nothing (it return immediatly without error) 
harbor-app/dd8ef857-68d0-4ca0-97fe-ede05180321c:/var/vcap/sys/log/harbor# /var/vcap/jobs/bosh-dns/bin/wait
harbor-app/dd8ef857-68d0-4ca0-97fe-ede05180321c:/var/vcap/sys/log/harbor#

**Comment by jessehu** [comment]
Could you run 'bosh deploy ... harbor.yml ...' again to see if it succeeded? I have no idea why "/var/vcap/jobs/bosh-dns/bin/wait" does not exist when /var/vcap/jobs/harbor/bin/pre-start runs.

**Comment by obeyler** [comment]
I try  to deploy again and I 've tail -f on harbor log

I see that harbor service does'nt start 
==> /var/vcap/sys/log/harbor/cron.log <==
curl -s --cacert /var/vcap/jobs/harbor/config/ca.crt https://harbor/api/systeminfo
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[Mon May 28 09:34:23 UTC 2018] Harbor status check: [FAILED]

==> /var/vcap/sys/log/harbor/ctl.stdout.log <==
[Mon May 28 09:35:24 UTC 2018] Harbor service is not ready. Waiting for 5 seconds then check again.

**Comment by robbo10** [comment]
@jessehu @obeyler Did you guys manage to resolve the above issue, im also getting the same error..

Thanks

**Comment by jessehu** [comment]
@obeyler BTW you used 'harbor' as the hostname for Harbor. It's better to use something like 'harbor.my.local'.

**Comment by suppalapati13** [comment]
@jessehu I have been working with @robbo10 on this. 
We found that the `No JSON object could be decoded` error message occurs when the following command fails..
`curl -s --cacert /var/vcap/jobs/harbor/config/ca.crt https://harbor-test.mydomain.com/api/systeminfo` 

In our case this was failing due to the following reasons
 - DNS name `harbor-test.mydomain.com` does not exist
 - hostname `harbor-test.mydomain.com` does not match the CN on the SSL certificate used.

Once the above issues are resolved, we were able to get all the services running on the bosh vm.

**Comment by jessehu** [comment]
@suppalapati13  With the bosh addon (https://github.com/vmware/harbor-boshrelease/blob/master/manifests/runtime-config-harbor.yml ), the bosh-dns-server on the harbor VM node is able to resolve harbor-test.mydomain.com to the VM IP.

**Comment by suppalapati13** [comment]
@jessehu thank you for the suggestion. We were able to resolve the DNS as suggested above.

**Comment by obeyler** [comment]
To my part it still failed
when I look inside the log It seems to not reach the harbor service :  I've got lot of Harbor service is not ready.
then 

`Recreating harbor-jobservice ... 
Recreating harbor-jobservice
Recreating nginx ... 
Recreating nginx ... done
[Wed Jun 27 07:11:51 UTC 2018] Harbor service is not ready. Waiting for 5 seconds then check again.
Recreating harbor-jobservice ... done
Attaching to harbor-log, registry, redis, clair-db, clair, notary-db, harbor-db, notary-signer, notary-server, harbor-adminserver, harbor-ui, nginx, harbor-jobservice
`

**Comment by jessehu** [comment]
@obeyler Need to check logs in /var/vcap/sys/log/harbor/cron.log on the Harbor VM

**Comment by obeyler** [comment]
[Wed Jun 27 11:36:20 UTC 2018] Harbor status check: [FAILED]
curl -s --cacert /var/vcap/jobs/harbor/config/ca.crt https://harbor.nd-int-ops-paas.itn/api/systeminfo
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[Wed Jun 27 11:36:25 UTC 2018] Harbor status check: [FAILED]

**Comment by jessehu** [comment]
Please run `curl --cacert /var/vcap/jobs/harbor/config/ca.crt https://harbor.nd-int-ops-paas.itn/api/systeminfo` to check detail error.

**Comment by obeyler** [comment]
curl --cacert /var/vcap/jobs/harbor/config/ca.crt https://harbor.nd-int-ops-paas.itn/api/systeminfo
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.11.13</center>
</body>
</html>

**Comment by jessehu** [comment]
Could you please attached log files in /var/log/harbor/ or email to me, and also check the docker container by running this command:

```
alias docker='/var/vcap/packages/docker/bin/docker -H unix:///var/vcap/sys/run/docker/dockerd.sock'
docker ps
```

**Comment by obeyler** [comment]
```
harbor-app/181f6d85-eefd-4f49-b364-b78b6d904b04:~# alias docker='/var/vcap/packages/docker/bin/docker -H unix:///var/vcap/sys/run/docker/dockerd.sock'
harbor-app/181f6d85-eefd-4f49-b364-b78b6d904b04:~# docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED              STATUS                        PORTS                                                              NAMES
d114b29d60fc        vmware/harbor-jobservice:v1.5.0             "/harbor/start.sh"       About a minute ago   Up About a minute                                                                                harbor-jobservice
c3c0a9cd9f5e        vmware/nginx-photon:v1.5.0                  "nginx -g 'daemon ..."   About a minute ago   Up About a minute (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4443->4443/tcp   nginx
f83b1c8f82b6        vmware/harbor-ui:v1.5.0                     "/harbor/start.sh"       About a minute ago   Up About a minute (healthy)                                                                      harbor-ui
b3a50b00bfbc        vmware/harbor-adminserver:v1.5.0            "/harbor/start.sh"       About a minute ago   Up About a minute (healthy)                                                                      harbor-adminserver
d19184bf48a3        vmware/notary-server-photon:v0.5.1-v1.5.0   "/bin/server-start.sh"   5 days ago           Up About a minute                                                                                notary-server
b425e541f869        vmware/clair-photon:v2.0.1-v1.5.0           "/docker-entrypoin..."   5 days ago           Up About a minute (healthy)   6060-6061/tcp                                                      clair
ad250f04cbe0        vmware/notary-signer-photon:v0.5.1-v1.5.0   "/bin/signer-start.sh"   5 days ago           Up About a minute                                                                                notary-signer
0c30d41c0cd9        vmware/harbor-db:v1.5.0                     "/usr/local/bin/do..."   5 days ago           Up About a minute (healthy)   3306/tcp                                                           harbor-db
94a2013f5d09        vmware/postgresql-photon:v1.5.0             "/entrypoint.sh po..."   5 days ago           Up About a minute (healthy)   5432/tcp                                                           clair-db
40441fcae30c        vmware/redis-photon:v1.5.0                  "docker-entrypoint..."   5 days ago           Up About a minute             6379/tcp                                                           redis
5654e577520b        vmware/registry-photon:v2.6.2-v1.5.0        "/entrypoint.sh se..."   5 days ago           Up About a minute (healthy)   5000/tcp                                                           registry
8a3be1972792        vmware/mariadb-photon:v1.5.0                "/usr/local/bin/do..."   5 days ago           Up About a minute             3306/tcp                                                           notary-db
2b7c70a5fc17        vmware/harbor-log:v1.5.0                    "/bin/sh -c /usr/l..."   5 days ago           Up About a minute (healthy)   127.0.0.1:1514->10514/tcp                                          harbor-log
harbor-app/181f6d85-eefd-4f49-b364-b78b6d904b04:~# 


```

**Comment by jessehu** [comment]
It shows all harbor container are up and running. Could you please attached log files in /var/log/harbor/ or email to me ?  Not sure why nginx returns 301.

**Comment by obeyler** [comment]
I see inside the mysql.log this :
Jun 27 10:53:51 172.18.0.1 mysql[29314]: 2018-06-27 10:53:51 139796355233536 [Warning] Aborted connection 12 to db: 'registry' user: 'root' host: 'harbor-ui.harborapp_harbor' (Got timeout reading communication packets)

**Comment by obeyler** [comment]
and in jobservice.log :
`Jun 27 10:43:43 172.18.0.1 jobservice[29314]: 2018-06-27T10:43:43Z [FATAL] [service_logger.go:73]: Failed to initialize job context: Get http://adminserver:8080/api/configurations: dial tcp: lookup adminserver: no such host
Jun 27 10:43:44 172.18.0.1 jobservice[29314]: 2018-06-27T10:43:44Z [FATAL] [service_logger.go:73]: Failed to initialize job context: Get http://adminserver:8080/api/configurations: dial tcp: lookup adminserver: no such host
Jun 27 10:43:45 172.18.0.1 jobservice[29314]: 2018-06-27T10:43:45Z [FATAL] [service_logger.go:73]: Failed to initialize job context: Get http://adminserver:8080/api/configurations: dial tcp: lookup adminserver: no such host
Jun 27 10:43:46 172.18.0.1 jobservice[29314]: 2018-06-27T10:43:46Z [FATAL] [service_logger.go:73]: Failed to initialize job context: Get http://adminserver:8080/api/configurations: dial tcp: lookup adminserver: no such host`

**Comment by jessehu** [comment]
Did you follow https://github.com/vmware/harbor-boshrelease#make-a-deployment-with-pre-build-final-release to create harbor deployment ? Please paste your bosh command and the manifests/harbor.yml file.

If you follow https://github.com/vmware/harbor-boshrelease#make-a-deployment-with-dev-release , please

**Comment by suppalapati13** [comment]
@obeyler Does it help if you set the following property to `true`?
```yaml
  populate_etc_hosts:
    description: "Whether to add IP to hostname mapping for Harbor instance in /etc/hosts."
    default: false
```

**Comment by obeyler** [comment]
The trouble is solved we used to have confict with routeregistrar in tls with the harbor tls

**Comment by obeyler** [comment]
thanks for your help
