### ISSUE TITLE
error into deployment_vsphere-withall.yml

### ISSUE THREAD

**Issue by obeyler** [vmware/harbor-boshrelease#2]
inside template/deployment_vsphere-withall.yml

line 31
 - name: docker
release: harbor

Release harbor doesn't exist

**Comment by jessehu** [comment]
/cc @steven-zou to take a look.
Thanks @obeyler for your interests on harbor-boshrelease. Welcome any kind of contribution to harbor-boshrelease project.

**Comment by jessehu** [comment]
Fixed in latest commit.
