### ISSUE TITLE
Fix "bosh sync-blobs"

### ISSUE THREAD

**Issue by drnic** [vmware/harbor-boshrelease#3]
Normal users of the release should not need to run `scripts/add_blobs.sh` - only CI would run a variation of this when a new upstream blob is discovered (e.g. new version of Harbor).

A normal user should just run `bosh sync-blobs`.

To fix this, as a committer, please run:

```
scripts/add_blobs.sh # which runs the bosh add-blob commands
bosh upload-blobs
git add config/blobs.yml
git commit -m "added all the blobs"
```
Then update the README to remove this section on fetching blobs and/or change it to say `bosh sync-blobs`.

And you're good to go.

**Comment by jessehu** [comment]
Hi @drnic does it require a public storage (like S3) specified for blobstore_path in config/final.yml ? Per the current setting "blobstore_path: /tmp/harbor-blob-store", 'bosh upload-blobs' upload blobs to local file system.

**Comment by drnic** [comment]
Have a look at https://github.com/cloudfoundry-community/redis-boshrelease/blob/master/config/final.yml#L3-L5

You'll also want to setup the S3 bucket policy so all objects are public.

Try out https://github.com/cloudfoundry-community/bosh-gen `bosh-gen new vmware-harbour-boshrelease` in a /tmp and it will guide you to create the S3 bucket + the `config/final.yml` and your private `config/private.yml` which you can then copy back into this project.

**Comment by jessehu** [comment]
Fixed by https://github.com/vmware/harbor-boshrelease/commit/8bdc83d2a0a0068e51597d28bdeafd6beaeef85d
Use GCS to store the blobs.
