### ISSUE TITLE
Can a new release bosh release be cut for 1.5.3?

### ISSUE THREAD

**Issue by Scoobed** [vmware/harbor-boshrelease#33]
Can a new release bosh release be cut for 1.5.3? as this release currently looks to point to 1.5.0 release on the master branch.  Or is the 1.6 version to be the latest one?  Looking for what the best version to be running at.  Other repo is https://github.com/goharbor/harbor/releases

**Comment by robbo10** [comment]
@jessehu  +1 for an update of the bosh release to be cut 👍

**Comment by jessehu** [comment]
@Scoobed @robbo10 The harbor-boshrelease 1.6 will be released soon. Can we cut a 1.6 release ?

**Comment by robbo10** [comment]
@Jessehu that would be great, would you have an estimated timeframe?

**Comment by jessehu** [comment]
We don't have the exact date yet. Before that, you may create your local harbor bosh release with lastest master branch code.

**Comment by robbo10** [comment]
Hey @jessehu - when trying to build a local release run into the following now:

`         Collecting package files:
            Missing files for pattern 'smoke-test/smoke-test'`

Looks like it comes from a private repo though ?

Thanks

**Comment by shinji62** [comment]
@jessehu When do you expect to cut a 1.6.X  release  ??
Seems pretty long time no ?

Thanks

**Comment by jessehu** [comment]
Hi @stonezdj @reasonerjt Could you please cut a 1.6.x release per @shinji62 request?

**Comment by stonezdj** [comment]
Add tag v1.6.2

**Comment by Scoobed** [comment]
Are you going to tag as Latest?

**Comment by shinji62** [comment]
@jessehu Tag is not enough ....

You should provide the final bosh release too. See the last one was 1.5.0 See 
 https://bosh.io/releases/github.com/vmware/harbor-boshrelease?all=1

**Comment by jessehu** [comment]
We have created 1.6.2 final release. But not sure why it doesn't show up on https://bosh.io/releases/github.com/vmware/harbor-boshrelease

**Comment by shinji62** [comment]
I guess you need to create github release https://github.com/vmware/harbor-boshrelease/releases not only tag

**Comment by jessehu** [comment]
@shinji62 https://github.com/vmware/harbor-boshrelease/releases/tag/v1.6.2 created. Let's see if bosh.io picks it up. 

@Scoobed https://github.com/goharbor/harbor/releases/latest now points to releases v1.6.2

**Comment by jessehu** [comment]
https://bosh.io/releases/ still didn't pick up 1.6.2 release.
Here is the binary: https://storage.googleapis.com/harbor-bosh-releases/harbor-container-registry-1.6.2.tgz
