### ISSUE TITLE
last version 1.6.0 not public

### ISSUE THREAD

**Issue by obeyler** [vmware/harbor-boshrelease#36]
@jessehu @stonezdj The last version https://storage.googleapis.com/harbor-bosh-releases/harbor-container-registry-1.6.2.tgz
is not public could you change the permission ? :-)

![image](https://user-images.githubusercontent.com/23224162/49652524-92065f00-fa32-11e8-8b1e-dc45bffbe149.png)

**Comment by jessehu** [comment]
Read permission granted. Thanks @obeyler
