### ISSUE TITLE
LDAP Groups With Admin Privilege

### ISSUE THREAD

**Issue by obeyler** [vmware/harbor-boshrelease#45]
LDAP Groups With Admin Privilege is not yet avialable. So if you enable LDAP you cannot connect as admin anymore

**Comment by stonezdj** [comment]
This setting is user settings, for user settings, you'd better login to the harbor web console to set it, ldap_group_admin_dn can be specified in harbor tile 1.7 web admin console.

**Comment by obeyler** [comment]
But you cannot loggin to web admin console if you are not already an admin. 
In our case we have automatized the harbor creation with the harbor bosh release and fix the ldap parameter inside the manifest. As soon as the ldap option is selected you can not log as admin.
