### ISSUE TITLE
harbor-container-registry/1.5.2-build.8 Support Xenial Stemcell?

### ISSUE THREAD

**Issue by Muruganfly03** [vmware/harbor-boshrelease#65]
Hi Team,

I am using harbor-container-registry/1.5.2-build.8 in our environment which is using stemcell -
bosh-vsphere-esxi-ubuntu-trusty-go_agent/3541.34

Kindly confirm whether harbor-container-registry 1.5.2 version support Xenial stemcell?

**Comment by jessehu** [comment]
We didn't test Xenial against 1.5.x, but it should work.

**Comment by stonezdj** [comment]
Harbor tile 1.7.5 support Xenial stemcell
