### ISSUE TITLE
Latest harbor job depends on bosh-dns in pre-start script

### ISSUE THREAD

**Issue by mtthwcmpbll** [vmware/harbor-boshrelease#7]
The latest version of the `pre-start.erb` script has a line that waits for bosh-dns to be ready (https://github.com/vmware/harbor-boshrelease/blob/master/jobs/harbor/templates/bin/pre-start.erb#L158).  Trying to deploy a release built on this code with both the provided `deployment_vsphere.yml` and the more recently-updated `deployment_vsphere-uaa.yml` end up with an error:

```
/var/vcap/jobs/bosh-dns does not exist
```

The `harbor` job is also dependent on the `harbor-enable-bosh-dns` job in its monit file (https://github.com/vmware/harbor-boshrelease/blob/master/jobs/harbor/monit#L6).  Is there a way to get this up and running without the bosh-dns, or some required manifest changes to get this dependent job up and running?

**Comment by jessehu** [comment]
@mtthwcmpbll harbor job depends on bosh-dns to resolve FQDN. The deployment_vsphere.yml is not updated to add bosh-dns as a bosh add-on, which will let bosh-dns run on each bosh VM. Need to fix this.

**Comment by jessehu** [comment]
Fixed in https://github.com/vmware/harbor-boshrelease/commit/089c7c536b7ccb2aee67c54f4aad8f125e077169.
@mtthwcmpbll Please try it out.
