### ISSUE TITLE
error when try to deploy harbor

### ISSUE THREAD

**Issue by obeyler** [vmware/harbor-boshrelease#9]
Task 1264 | 10:09:23 | Preparing deployment: Preparing deployment (00:00:02)
	
Task 1264 | 10:09:26 | Preparing package compilation: Finding packages to compile (00:00:00)
	
Task 1264 | 10:09:27 | Updating instance harbor: harbor/005c587f-bf8a-4a8e-ab05-52fef0feae2c (0) (canary) (00:00:06)
	
                    L Error: Action Failed get_task: Task ee5e33ba-e400-4c1c-60ed-dbf5ae88a18b result: Stopping Monitored Services: Stop all services: Running command: 'monit stop -g vcap', stdout: '', stderr: 'monit: Error: Depend service 'harbor-enable-bosh-dns' is not defined in the control file

**Comment by jessehu** [comment]
@obeyler I pushed a commit https://github.com/vmware/harbor-boshrelease/commit/089c7c536b7ccb2aee67c54f4aad8f125e077169 today to fix the harbor bosh dns issue. Please follow the lastest README.md on master branch.

**Comment by jessehu** [comment]
Please follow lastet guide to upload runtime config bosh dns and use https://github.com/vmware/harbor-boshrelease/blob/master/manifests/deployment-vsphere.yml to deploy harbor bosh release. Reopen this issue in case it doesn't work.

**Comment by obeyler** [comment]
ReOpen : sorry I already use it
